mqtt:
  host: tcp://192.168.1.17:1883
  client:
    clientid: share
    user-name: admin
    password: public
    time-out: 10
    alive-time: 60
    max-connect-times: 10
    topics: ["tyzw_scppro_cardLog","tyzw_scppro_queryStatus_return","tyzw_js_return","tyzw_scppro_dev_info_return","tyzw_scppro_time_info_return",
             "tyzw_scppro_status_return","tyzw_scppro_ctl_return","tyzw_scppro_add_teacher_return","tyzw_scppro_add_students_return",
             "tyzw_scppro_energyClearZero_return","tyzw_scppro_modifyName_return"]
    qos: [2,2,2,2,2,2,2,2,2,2,2]
  pool:
    min-pool-size: 1
    max-pool-size: 3
    oversee-interval: 5000

spring:
  datasource:
    url: jdbc:mysql://192.168.1.108:3306/share19?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: ygbx123#
    driver-class-name: com.mysql.cj.jdbc.Driver
  #自定义命名规则
  jpa:
    hibernate:
      naming:
        physical-strategy: com.wangxl.mqttpool.config.TableNameStrategy
  jackson:
    time-zone: GMT+8
server:
  port: 18189


